### ISSUE TITLE
batch_extract not working?

### ISSUE THREAD

**Issue by dloewensteiner** [rasenior/ThermStats#7] opened 2020-10-15 02:08 UTC
I'm having an issue with batch_extract working. I can read in the files using readflirJPG and am pointing to the exiftool. But when I use batch_extract I'm getting a series of errors: 

Processing file 1 of 4 
Reading file... 
Error: File not found - C:/Users/rle/Documents/Test/FLIR20201002_112748_650_R.JPG.jpg
Couldn't process file: C:/Users/rle/Documents/Test/FLIR20201002_112748_650_R.JPG.jpg

It looks like it sees the FLIR images in that folder, but then says it can't find them and can't process them.

**Comment by rasenior** [comment] 2020-10-19 08:39
Odd! Would you be able to share an example image with me (rebecca.a.senior@gmail.com)? And could you send me the output of `sessionInfo()`? I'll take a look and see if I can figure it out.

**Comment by rasenior** [comment] 2020-10-28 16:41
Sorry this has taken so long - think it's fixed now! Was caused by a silly bit of inflexibility in the format of file names accepted by `batch_extract`, which I have now resolved. Can you let me know if it works for you now @dloewensteiner?

**Comment by dloewensteiner** [comment] 2020-10-30 00:33
Fixed it! Thanks!

**Comment by rasenior** [comment] 2020-10-30 09:14
Excellent. Thanks for letting me know.

**Closed by rasenior** 2020-10-30 09:14 UTC
